# Setup
title:               Chitrakaavyas
tagline:             ''
description:         'An effort to appreciate the beauty of language'
url:                 https://vrraghy.github.io
#baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raghavan
  url:               https://twitter.com/vrraghy
  email:             vrraghy@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
